# PB UNIT - 4 QUESTIONS
- SIMPLE LINEAR REGRESSION PROGRAMS - 215,216,220,221,223
- MULTIPLE LINEAR REGRESSION PROGRAMS 217,224,225,226,227,229
- POLYNOMIAL REGRESSION PROGRAMS - 218,219,230
### 215

For x = np.array([5, 15, 25, 35, 45, 55]) and y = np.array([5, 20, 14, 32, 22, 38]), apply simple linear regression using scikit learn library and calculate calculate R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

---

### import libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [10]:
# Features and target
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1,1)
y = np.array([5, 20, 14, 32, 22, 38])
print(x.shape)
print(y.shape)

(6, 1)
(6,)

In [11]:
# Create model
model = LinearRegression()

In [14]:
# Fit the model
model.fit(x,y)

LinearRegression()

### 216

Given a dataset with 'SAT' scores as independent variables and 'GPA' as the dependent variable, calculate R squared, coeficient and intercept using linear regression and scikitlearn library. (Don't split data for training/testing)

---

Type help() for interactive help, or help(object) for help about object.

### 217

Given a real estate price size year dataset, implement multiple linear regression using scikitlearn library. Using the model, make a prediction about an apartment price with size 750 sq.ft. for 2009.Also Calculate R squared, coeficient and intercept. (Don't split data for training/testing)

---

### MULTIPLE LINEAR REGRESSION
- The price column is dependent variable
- The size

In [2]:
data = pd.DataFrame({
    'size' : [2104,1600,2400,1416,3000],
    'year' : [2003,1977,2001,1995,2000],
    'price' : [399900,329900,369000,232000,539900]
})

In [4]:
x = data[["size","year"]]
y = data["price"]
print(x.shape)
print(y.shape)

(5, 2)
(5,)

In [5]:
# Create and fit model
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [8]:
# Print R2 score, coefficient and interce
print(model.score(x,y))
print("The slope is",model.coef_[0])
print("The intercept is",model.intercept_)

0.9110630594451152
The slope is 187.88485815154039
The intercept is 4778064.714300399

In [9]:
newdata = pd.DataFrame({
    'size' : [750],
    'year' : [2009]
})
prediction = model.predict(newdata)
print("Prediction for 750 SqFt house with 2009 year is",prediction[0])

Prediction for 750 SqFt house with 2009 year is 86549.5177951986

### 218

Predict salary based on job position of 6.5 using polynomial regression with a degree of 3 and scikit learn library for the given 'Position_Salaries.csv' dataset. (Don't split data for training/testing)

---

In [ ]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# import dataset
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/Position_Salaries.csv")
df.head(2)

# Define features and target
x = df[["Level"]]
y = df["Salary"]
print(x.shape)
print(y.shape)

# Create polynomial feature
poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)

# Create and fit model
model = LinearRegression()
model.fit(x_poly,y)

# Prediction
level = np.array([[6.5]])
level_poly = poly.fit_transform(level)
predicted_salary = model.predict(level_poly)
print(predicted_salary)

### 219

For x = np.arange(0, 30) and y = np.array([3, 4, 5, 7, 10, 8, 9, 10, 10, 23, 27, 44, 50, 63, 67, 60, 62, 70, 75, 88, 81, 87, 95, 100, 108, 135, 151, 160, 169, 179]), apply polynomial regression using scikit learn library and calculate R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

---

In [ ]:
# import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Define features and target
x = np.arange(0, 30).reshape(-1,1)
y = np.array([3, 4, 5, 7, 10, 8, 9, 10, 10, 23, 27, 44, 50, 63, 67, 60, 62, 70, 75, 88, 81, 87, 95, 100, 108, 135, 151, 160, 169, 179])
print(x.shape)
print(y.shape)

# Create polynomial feature
poly = PolynomialFeatures(degree=3) # by default degree=3
x_poly = poly.fit_transform(x)

# Create and fit model
model = LinearRegression()
model.fit(x_poly,y)

# Evaluation metrics
print("R2 score =",model.score(x_poly,y))
print("The coefficients =",model.coef_)
print("The intercept =",model.intercept_)

# Prediction
level = np.arange(5).reshape(-1,1)
level_poly = poly.fit_transform(level)
predicted_values = model.predict(level_poly)
print(predicted_values)

### 220

Write a program to make a model based on linear regression for the following dataframe created from a csv file named “Package.csv” of x and y which follows equation y = a + bx. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation.
Given Data in csv file:

| cgpa | package |
| ---- | ------- |
| 6.89 | 3.26    |
| 5.12 | 1.98    |
| 7.82 | 3.25    |
| 7.42 | 3.67    |
| 6.94 | 3.57    |
| 7.89 | 2.99    |
| 6.73 | 2.60    |
| 6.75 | 2.48    |
| 6.09 | 2.31    |
| 8.31 | 3.51    |
| 5.32 | 1.86    |
| 6.61 | 2.60    |
| 8.94 | 3.65    |
| 6.93 | 2.89    |
| 7.73 | 3.42    |

---

### 221

Write a program to make a model based on linear regression for the following dataframe created from a csv file named “data.csv” of x1 and y which follows equation y = a+bx1. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation.
Given Data in csv file:

| y   | x1 |
| --- | -- |
| 140 | 60 |
| 155 | 62 |
| 159 | 67 |
| 179 | 70 |
| 192 | 71 |
| 200 | 72 |
| 212 | 75 |
| 215 | 78 |

---

### 222

Write a program to create a Model using linear regression to predict the price of house using the csv file provided named “Housing.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

### 223

Write a program to create a Model using linear regression to predict the student scores using the csv file provided named “student_scores.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

### 224

Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “petrol_consumption.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

In [1]:
# import csv
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/petrol_consumption.csv")
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [2]:
x = df[["Petrol_tax","Average_income","Paved_Highways","Population_Driver_licence(%)"]]
y = df["Petrol_Consumption"]
print(x.shape)
print(y.shape)

(48, 4)
(48,)

In [4]:
from sklearn.linear_model import LinearRegression
# Create and fit model
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [5]:
# Print coefficient and interce
print("The slope is",model.coef_)
print("The intercept is",model.intercept_)

The slope is [-3.47901492e+01 -6.65887518e-02 -2.42588889e-03  1.33644936e+03]
The intercept is 377.2911464736735

In [6]:
from sklearn.metrics import mean_squared_error,r2_score
prediction = model.predict(x)
print("Predicted value =",prediction)
print("R2 score =",r2_score(y,prediction))
print("MSE =",mean_squared_error(y,prediction))

Predicted value = [523.23372749 553.11530293 578.10744578 493.35625176 532.02892629
 433.55141589 318.73259324 491.50595563 489.02463498 550.39466272
 500.48954932 442.25333892 563.31260606 566.0237744  638.06601138
 604.30550439 597.49738202 596.40345112 772.9677508  682.70972973
 694.9794757  570.24033097 415.07930617 460.22150127 507.02812076
 531.91824029 588.64881068 612.08788703 558.02256272 471.98285862
 566.90705013 581.42200158 651.64983584 613.86729832 506.41719219
 716.82376287 647.28207972 641.93375943 717.64832948 733.05284779
 662.87034473 633.06544672 644.48932597 556.96750449 713.79948278
 519.67828001 670.3978699  569.438479  ]
R2 score = 0.6786867115698209
MSE = 3938.5410046485035

### 225

Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error. (Wherever required remove null values, convert categorical data into numeric data)

---

In [7]:
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/FuelConsumptionCo2.csv")
df.head(2)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

In [8]:
df.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [11]:
df = pd.get_dummies(df)
df.head(2)

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,MAKE_ACURA,MAKE_ASTON MARTIN,...,TRANSMISSION_AV6,TRANSMISSION_AV7,TRANSMISSION_AV8,TRANSMISSION_M5,TRANSMISSION_M6,TRANSMISSION_M7,FUELTYPE_D,FUELTYPE_E,FUELTYPE_X,FUELTYPE_Z
0,2014,2.0,4,9.9,6.7,8.5,33,196,True,False,...,False,False,False,False,False,False,False,False,False,True
1,2014,2.4,4,11.2,7.7,9.6,29,221,True,False,...,False,False,False,False,True,False,False,False,False,True

In [12]:
df.shape

(1067, 752)

In [13]:
# Features and target
x = df.drop(columns = ['CO2EMISSIONS'],axis = 1)
y = df["CO2EMISSIONS"]
print(x.shape)
print(y.shape)

(1067, 751)
(1067,)

In [14]:
# Create and fit model
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [15]:
# Print coefficient and interce
print("The slope is",model.coef_)
print("The intercept is",model.intercept_)

The slope is [-1.10774833e-12  3.63821177e+00  4.22585069e-01 -3.52562376e+00
 -5.74449866e+00  1.72452190e+01 -5.13928441e+00 -5.18297185e+00
  3.32350437e+00  5.70547461e-01  1.00528049e+01 -6.21724497e+00
 -5.07143226e+00 -5.66377370e+00 -3.60051140e+00 -7.92365928e+00
 -6.71900446e+00  5.78187912e+00  1.50449529e+00 -4.61758444e+00
  5.60521986e+00  2.04503528e+00 -7.43567699e+00 -4.98334878e+00
 -1.30739933e+00 -1.01862492e+00  1.75694595e+01  2.70466368e+00
 -2.81880855e+00 -2.97263221e-01  2.50786412e+00  3.71788049e+00
 -5.36057512e+00  6.06756000e-01  6.27764340e-01 -2.63058379e+00
 -9.69362534e+00 -4.65923657e+00  1.05004913e+01  3.29925142e+00
  1.04347982e+01  4.06973804e+00 -1.41055185e+00  8.01337122e+00
 -2.75257794e-01 -6.04838992e+00 -9.27822457e-01  2.44475871e+00
  1.63584111e+00 -1.30140765e+00 -1.38739823e+00 -2.41548029e+00
 -8.31877321e+00 -2.63409070e+00 -2.63579686e+00 -1.34972587e+00
 -1.70445697e+00 -4.40186993e+00 -4.94427070e+00  6.92012575e-01
 -7.77400437e-01  2.89474608e+00 -1.72475943e+00 -2.86190845e+00
  2.39659630e-01 -1.06690864e+00  1.32108507e+01  1.56492319e+01
  2.39659630e-01 -1.82060950e+00  4.25194141e+00  6.17771691e-01
 -9.24665391e+00 -6.69971266e+00 -7.15602883e-01 -8.29545029e+00
 -8.54003873e+00  2.39659630e-01 -1.82060950e+00 -9.24665391e+00
 -6.69971266e+00 -1.24202913e+01 -1.24202913e+01 -4.60172647e-01
 -4.60172647e-01  4.61481277e+00 -4.60172647e-01  9.09503988e+00
 -4.60172647e-01 -6.08728294e+00 -1.35568744e-01 -8.89269608e-01
  9.39886235e-01 -5.85681390e+00 -1.77922963e+00 -6.70160515e+00
 -1.05801404e+00 -6.78815380e+00 -3.50296827e+00 -7.63294505e+00
 -7.13056496e+00 -1.77922963e+00 -1.05801404e+00 -1.05801404e+00
  9.39721172e+00 -4.13400710e+00 -5.17744015e+00 -1.06027054e+00
 -3.50334943e+00 -2.77895469e+00 -4.31028829e+00 -4.12591284e+00
 -4.81678351e+00  8.56697303e+00  3.82435566e-02  3.82435566e-02
  3.82435566e-02  3.82435566e-02 -3.45920217e+00 -9.02172502e+00
 -3.95515472e+00 -5.39412833e+00 -5.90807126e+00 -7.28809770e+00
 -9.58476234e+00 -7.28809770e+00 -1.15580394e+01 -5.30749484e+00
  1.66311601e+00 -3.10307789e+00 -4.01728265e+00 -5.16074858e-01
  3.15635658e+00 -1.67062972e+01  6.60364300e+01 -6.00286139e-01
 -5.29239304e+00  2.98927469e+00 -1.82742792e+00 -1.05801404e+00
 -1.05801404e+00 -1.05664174e+01  1.53512786e+01 -5.38655299e+00
 -5.51957143e+00 -2.37589431e+01 -2.55438069e+00 -2.90911178e+00
  2.08989617e+01  5.70248706e+00 -7.19847177e+00 -3.67251759e+00
  2.60418589e+00 -5.24226291e-03 -5.10591868e+00 -3.83436066e+00
 -2.68437120e+00  7.21337995e-01 -5.91792102e+00 -7.90496079e+00
 -9.53300127e+00 -3.07487376e+00 -3.92480172e+00  5.03731575e+00
  7.50505858e+00  3.27024993e+01 -3.89064846e+00 -1.15535378e+01
 -1.15802646e+01 -1.59586131e+01  7.73582699e+00 -1.84208111e+01
  2.95999136e+01  1.87895315e+01  5.61104545e+00  5.10354977e+00
  1.50047258e+00  3.32159234e+00  3.52197918e-01  1.21510163e+00
  4.03767121e+00 -5.24226291e-03 -5.10591868e+00 -8.28857602e+00
 -8.31280478e+00 -6.62383744e+00 -1.12901365e+01 -6.84634158e+00
 -9.20777429e+00 -4.14935146e+00 -6.14892552e+00 -5.12642240e-01
 -1.98205525e+00  1.69009126e+00  1.15729503e-01 -4.06656327e+00
 -7.66506115e-01 -2.15635893e+00  6.56489014e-01  1.07346512e+00
 -2.37883171e+00 -6.18656436e+00 -5.09947838e+00  4.20207223e+00
  7.84289990e-01 -9.46086303e+00 -4.56766500e+00 -4.56766500e+00
  2.01299263e+00  2.20962291e+00 -4.79981570e+00 -9.53978823e+00
 -9.45110229e+00  3.52325482e+00 -2.14079107e+00  4.67732676e+00
  3.43108950e+00 -1.52129483e+00  7.96368057e+00 -1.52129483e+00
  1.70843435e+00  2.23334138e+00  9.87104117e-01 -4.40746809e+00
 -7.35551036e-01 -4.40746809e+00 -7.35551036e-01 -3.00061797e+00
  3.09566842e+00  1.30777409e+00 -7.58908265e+00 -2.04065480e+01
 -7.05187021e+00 -7.58368358e+00  1.34290195e+01 -1.39754670e+01
  2.28222679e+00  6.38894832e+00  1.31839036e+01  4.11975738e+01
 -8.57747368e+00 -5.95060550e+00 -5.17515031e+00 -5.20419334e+00
  8.26624220e-01 -3.60329072e+00 -4.85949884e+00  1.07304292e+01
  1.07304292e+01  1.22374705e+01  5.82009566e-01  1.68183796e-02
 -5.19047655e+00 -4.70406507e+00  2.15766209e+00  6.03686845e+00
  2.43645887e-01  1.68129678e+01  2.09015450e+00  1.27825708e+00
 -3.04177231e+00  6.00027710e+00 -6.66369501e+00 -9.49422583e+00
 -6.47985445e+00 -9.31249545e+00 -6.12729207e+00 -3.61487584e+00
 -4.44297268e+00 -1.30589919e+01 -8.58579491e+00 -8.62843140e+00
 -6.83764315e+00 -6.23153494e+00 -6.83764315e+00 -6.23153494e+00
  9.41282528e-01 -6.61600726e+00  3.01603749e+01 -1.19797678e+00
 -5.19188280e+00 -3.54324865e+00 -4.57288306e+00 -3.56343483e+00
 -4.09524820e+00  1.00815417e+01  1.07948552e+01 -4.94831981e+00
  3.06978898e+00  3.94629929e+00 -8.49937916e+00  3.49785040e+01
 -1.29267633e+01  7.07627443e-02  1.28404137e+01 -2.99141093e+00
 -1.83471929e+00  7.69642425e+00 -7.56692877e+00 -5.60287945e+00
 -9.60363368e+00 -6.60359818e+00 -8.97607192e-01  1.75854658e+00
  9.16602924e-01  2.96065762e+00 -1.01068571e+01 -8.06280238e+00
  7.79748654e+00  9.91954867e+00 -6.38534618e+00 -1.42531277e+00
 -4.69431572e+00 -3.84377341e+00  3.30040889e+00 -6.01286061e+00
 -1.32348158e+00  2.60620290e+01  6.51121381e+00  1.86095344e+01
 -2.20487761e+00  4.05388272e+00 -2.78733735e+00 -1.24260440e+01
 -1.26933334e+01 -8.87718525e+00  8.26998026e-01 -5.56870254e+00
  2.31074827e+00  7.84462436e+00 -1.65732430e+00 -3.06235035e-01
  2.63232668e+00 -3.18692165e+00  5.21739912e+00  5.21739912e+00
 -5.43108869e+00  2.07225029e+00  6.12585968e+00 -5.91722346e+00
 -1.23890961e+00 -9.34395054e+00  3.96621992e+01  4.08325952e+01
  3.41909307e+01 -3.32950228e+00 -1.33130779e+01 -6.80835186e+00
 -6.80835186e+00 -1.20212638e-01 -1.20212638e-01  1.32484937e+01
  1.38644200e+01  1.43132095e+01  1.40295083e+01  7.05358043e+00
  1.19881821e+00 -6.96440036e+00  5.57379431e+00  7.18230587e+00
 -2.00067126e+00 -3.78684929e+00 -8.45337745e+00  5.12976279e+00
  4.80703530e+00  2.94205670e+00 -9.33764130e+00 -7.97953825e+00
  6.19331848e+00  4.53871607e-01 -1.77314631e+00 -1.32045399e+01
 -1.79166951e+01 -1.41602954e+01 -1.47883359e+01 -3.38735588e+00
  3.57821709e+01 -1.79118427e+00 -2.48106158e-01 -3.45555930e+00
 -1.01717810e+00 -9.48718763e+00 -8.55198667e+00 -5.85959094e+00
 -6.06766315e+00 -8.91087814e+00 -5.95395843e+00 -6.42561911e+00
 -5.02686653e+00 -6.66053197e+00  5.47096200e+00  4.99759352e+01
  2.23334138e+00  9.87104117e-01 -4.40746809e+00 -7.35551036e-01
 -4.40746809e+00 -7.35551036e-01  3.68399900e+00  7.34375632e+00
  6.06860462e+00  2.32371771e+00 -5.67021975e+00 -4.60089522e+00
 -3.29582476e+00 -2.99716849e-01 -4.10777430e+00 -8.70225993e+00
 -5.28824515e-01 -8.83570252e+00 -2.06346742e+00 -7.63492321e+00
  2.50874428e+00  6.60667767e+00 -7.57855280e+00 -2.92844527e+00
 -2.92844527e+00 -6.19538657e+00  1.52389294e+01  2.55861187e+00
  1.62727197e+00  5.25486866e+00  1.62727197e+00 -1.05252167e+00
 -1.52399521e+01  3.91676146e+00  4.27687967e+00  5.15053344e+00
  2.95181809e+00  3.42389184e+00  3.77311975e+00  3.53059561e+00
 -2.80163449e+00 -4.62626889e+00  3.08682063e+00 -3.38674632e+00
  2.59399711e+01 -6.33086791e+00 -7.07542674e+00  1.88089404e+00
 -1.50492721e+00 -9.15823350e-01 -8.21286901e+00 -1.06627123e+01
  2.30262865e+01 -1.25465167e+00 -3.42342660e+00  4.33136337e+00
  1.10147120e+01  2.68342337e+01 -5.39523611e+00 -1.34068346e+01
 -1.11529815e+01 -9.66892295e+00  9.49818276e+00 -2.36654134e+00
 -8.06271073e+00 -5.82656564e+00  3.35900953e+00 -2.62670720e+00
  2.00816763e+00 -2.57666801e+00 -7.33032209e-01 -2.89288606e+00
  2.47313420e+00  4.65622740e+00 -1.31836773e+00  2.47313420e+00
 -3.37764877e-01  1.86472547e+00 -7.13215957e+00  8.06888451e+00
 -7.40726702e+00 -7.08915243e+00 -8.98719337e+00  2.01299263e+00
  2.20962291e+00 -4.79981570e+00  8.92018825e+00  2.84763734e+00
  2.27318747e+00  8.34573838e+00 -7.78078628e+00 -6.12950646e+00
  6.43559210e+01  6.90272885e+01  3.17639785e+01 -4.22819718e-01
  6.45782879e+00  5.41394352e-01 -5.76001048e+00 -7.24918736e+00
  8.12600875e+00 -1.14437136e+00  1.72521743e+00 -6.97749427e-01
 -4.57831490e+00 -1.40934913e+00 -2.71321723e+00 -6.92128208e+00
 -6.00739937e+00  6.21176718e+00  4.89831777e+00  3.47715807e+00
 -8.34485955e+00 -1.57026130e+00 -2.71939796e+00 -2.62317086e+00
 -2.65028680e+00  1.02720484e+01  8.15071316e+00  2.22309302e+01
  2.22309302e+01 -1.19696272e+00 -1.19696272e+00  2.66976316e+00
  3.18433594e+00 -5.66293180e+00 -3.44594567e+00  3.23919853e+00
  9.82224903e-01 -6.86542214e+00 -3.97215483e+00  2.66976316e+00
  3.18433594e+00  3.33639176e+00 -5.98205540e+00 -9.60073486e+00
 -8.04568214e+00  1.01258260e-01 -2.14231435e+00 -4.25378527e+00
 -2.99716849e-01 -8.24495918e+00  5.90599653e+00  5.91386530e+00
 -1.12492595e+01  7.77151350e-02 -1.02854811e+00 -8.11316937e+00
 -2.52783655e+00  1.50556193e+01  1.72763345e+01 -1.10006824e+01
  2.77589920e-01 -7.83267613e-01 -1.50607944e+00  3.98374831e+00
 -5.91393869e+00 -1.97714463e+00 -2.89390798e+00  1.01155497e+00
  4.63915165e+00  1.09078234e+01  6.56373002e+00 -5.14334718e+00
 -2.88500989e+00  6.56373002e+00 -5.94943643e+00 -5.10451064e+00
 -5.87897162e-01 -6.24002288e+00 -5.92190828e+00 -4.55486898e+00
 -9.00044175e-02  1.19465842e-01  2.77561962e+00  1.93367596e+00
  3.97773065e+00 -9.08978403e+00 -7.04572934e+00  8.81455957e+00
  1.09366217e+01  3.97814564e+00  5.76528769e+00  7.72529184e+00
 -1.05104725e+01 -5.00542252e+00 -5.92225410e+00 -3.54023377e+00
 -6.93932714e+00 -4.55730680e+00 -1.08890248e+01 -9.94080960e+00
 -4.63128959e-01 -1.76370515e-01 -7.94134513e+00 -1.83240414e+01
  1.92887657e+01  9.99356517e+00  9.99356517e+00 -3.31481125e+00
  2.83695336e+01  2.38582897e+01  5.66880368e+00  6.35014357e+00
  7.08843468e+00  6.15709478e+00 -1.30757657e+00  1.77777966e+00
 -4.87262907e-01 -2.20676387e-01  2.08964172e+01 -1.46642328e-01
  2.25895961e+00  3.33083718e+00 -4.52035462e+00 -2.07273744e+00
 -6.74530586e+00 -6.74530586e+00 -8.36153857e+00 -4.98889925e+00
 -6.74530586e+00 -6.74530586e+00 -3.44903866e+00 -6.94316533e+00
 -8.00795754e+00 -5.67066246e+00  4.08686201e+00  4.96337233e+00
  3.16913672e-01  2.17936618e-01  7.28402678e+00  2.16514565e+01
 -9.02854435e+00 -9.18682346e+00 -6.25269323e+00 -5.51869180e+00
  1.15238614e+01  3.44430891e-01 -8.89957589e-01 -4.91804905e+00
 -5.03435569e+00 -5.56616906e+00  1.17372196e+01  5.91895360e+00
  8.69913824e+00 -4.82767146e+00 -2.95355810e+00 -5.92245052e+00
 -5.43337398e+00 -8.40226639e+00 -2.58666203e+00  9.55605453e-01
 -6.99352127e+00  4.75377154e-01 -2.09659819e+00 -2.09659819e+00
  2.09015450e+00 -6.92941928e-03 -5.19420261e+00 -1.22933688e+01
 -1.05695602e+01 -3.39689278e+00  1.26360998e+01  2.03486902e+00
  2.03486902e+00 -1.16458349e+01  3.06049787e+00  7.09054923e+00
  5.49804057e+00  2.60631240e+00  5.14271278e+00  4.51811554e+00
 -9.29036932e+00 -1.61503143e-01  2.44857378e+01 -1.01339362e+00
  3.03981490e+00  9.35124081e-02  4.99340397e+00  3.61463243e+00
 -1.02917386e+00  5.35539706e-01 -1.19030628e+00 -4.40294710e-01
 -3.14118750e+00  7.02154790e+00  2.09344528e+00  7.37411028e+00
  2.09344528e+00  1.77813603e+00  1.77813603e+00 -1.65619400e+00
 -9.11242071e+00  1.40123881e+00 -1.20740452e+00  1.40123881e+00
 -1.20740452e+00  1.25587287e+01 -2.04950682e+00 -8.04379985e-01
  6.23412458e-01  1.55277512e+00  8.56358756e+00  4.69112335e+00
 -5.72823282e+00 -5.72823282e+00 -9.75426520e-01  1.17942244e+01
 -5.72823282e+00 -5.72823282e+00 -1.71279025e+00 -3.51123100e+00
 -3.96630141e+00  2.56794464e+01 -1.31085941e+01 -6.52154091e+00
  2.68102876e+00  1.15146803e-01 -5.95740411e+00 -8.16193092e-01
 -2.26621262e+00 -8.95757797e+00 -5.15232785e+00  1.12529841e+00
 -7.45415025e+00  1.87524384e+00 -2.32323439e+00 -3.51244988e+00
 -7.20350327e+00  1.07551282e+00 -5.43557470e-01  1.44859745e+01
  2.55094345e+01 -1.14042748e-01  5.45501524e-01 -7.40456119e-01
 -1.90344015e+01 -3.05883682e-01 -1.19291091e+00  1.04347982e+01
  1.28580531e+00  1.75367817e+00  2.26000704e-01 -1.01670520e+00
  2.34355248e-01 -1.02962853e-01 -2.92697434e+00 -2.39392545e+00
  6.32594145e+00  9.69148638e-01  8.16853692e+00 -3.46127025e+00
  2.26000704e-01  3.86559156e-01  7.33206945e-01  4.80704517e+01
 -7.47788939e+01  1.31846652e+01  1.35237769e+01]
The intercept is 275.85637684151357

In [16]:
prediction = model.predict(x)
print("Predicted value =",prediction)
print("R2 score =",r2_score(y,prediction))
print("MSE =",mean_squared_error(y,prediction))

Predicted value = [192.47119099 224.52880901 136.         ... 269.69959517 261.30040483
 294.        ]
R2 score = 0.9986132474542174
MSE = 5.564046577788191

### 226

For the given RealEstate csv, write a python program satisfying following tasks to demonstrate application of machine learning through multiple linear regression as follows –

Dataset: RealEstate.csv
ML Library to be used: scikit-learn
Dependent variable: 'Y house price of unit area'
Independent variables: 'X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude' and 'X6 longitude'

1. Import required libraries.
2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
3. Remove ‘No’ column from the dataframe.
4. Check for any null values in features using appropriate method.
5. Create feature variables x and y as given above.
6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
7. Create and fit regression model using appropriate method.
8. Use testing set created in step 6 to find and print the prediction of the outcome.
9. Find and print coefficient and mean squared error of the regression model.

---

In [2]:
# 1. Import required libraries.
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
from sklearn.model_selection import train_test_split

In [18]:
# 2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/RealEstate.csv")
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB
None

In [19]:
# 3. Remove ‘No’ column from the dataframe.
df.drop(columns=["No"],inplace=True)
df.head(2)

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2

In [20]:
# 4. Check for any null values in features using appropriate method.
df.isnull().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [21]:
# 5. Create feature variables x and y as given above.
x = df.drop(columns=["Y house price of unit area"])
y = df["Y house price of unit area"]
print(x.shape)
print(y.shape)

(414, 6)
(414,)

In [23]:
# 6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=110)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(289, 6)
(125, 6)
(289,)
(125,)

In [24]:
# 7. Create and fit regression model using appropriate method.
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [25]:
# 8. Use testing set created in step 6 to find and print the prediction of the outcome.
y_pred = model.predict(x_test)
print(y_pred)

[40.06913335 32.56470479 29.80668902 44.60809493 39.96541473 44.34984726
 37.64834639 51.18801909 37.08044432 38.64449437 36.45757424 31.64776451
 43.03392987 16.64984039 36.61381207 31.21699197 39.55333345 41.89770923
 46.41953538 42.69067202 40.49560609 53.3447345  40.74436408 36.67049204
 46.86499408 42.78349352 47.25115307 40.53653503 42.57499139 50.88772177
 44.81813044 41.05114011 35.39386877 42.95199941 13.97578058 30.00463214
  0.32863779 39.56884707 47.9626967  34.0147913  40.23322474 49.74492584
 36.73990519 35.39784888 29.6071314  45.83432319 42.44745248 37.88237609
 31.55675944 47.517238   35.03089266 45.17666152 45.98711652 47.32685806
 54.18178829 15.18888047 43.78264851 44.75385635 37.69057227 39.34215811
 44.21812376 44.27270068 47.84570949 38.42626454 41.0626191  19.64522484
 47.9626967  43.85961508 37.99756745 43.80152052 42.39390912 42.57768877
 44.73329588 32.31758114 46.89135756 38.92015239 40.90438603 43.95669962
 34.28075691 25.5851042  16.26403643 45.66098257 42.05300968 10.81561309
 31.65043887 49.10789869 47.40016786 13.5604683  46.02203009 44.82145569
 34.76747867 35.40469328 31.48202917 45.59192922 42.0246353  42.54274755
 14.70678074 43.68554348 27.69149444 43.0460661  27.63908623 35.23545719
 45.89665228 50.31290226 42.86214486 44.61671482 49.59887911 32.11577476
 31.86965512 38.39003281 44.58865137 25.50284004 46.20113858 37.45131001
 14.70678074 44.2357441   9.25548578 37.23816575 38.97851394 47.40016786
 39.50115693 32.15412829 46.99435489 47.07907957 53.12308545]

In [26]:
# 9. Find and print coefficient and mean squared error of the regression model.
print("Coefficient =",model.coef_)
print("MSE =",mean_squared_error(y_test,y_pred))

Coefficient = [ 6.84308941e+00 -2.25466590e-01 -5.18046265e-03  1.12369103e+00
  1.87739728e+02 -4.29300312e+01]
MSE = 77.14802598253691

### 227

Write a program to create a Model using linear regression to predict the charges of insurance using the csv file provided named “insurance.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

In [27]:
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/insurance.csv")
df.head(2)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55

In [29]:
df = pd.get_dummies(df)
df.head(2)

,age,bmi,children,expenses,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.9,0,16884.92,True,False,False,True,False,False,False,True
1,18,33.8,1,1725.55,False,True,True,False,False,False,True,False

In [30]:
x = df.drop(columns=["expenses"],axis=1)
y = df["expenses"]
print(x.shape)
print(y.shape)

(1338, 11)
(1338,)

In [31]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [32]:
print("Coefficient =",model.coef_)
print("Intercept =",model.intercept_)
prediction = model.predict(x)
print("Predicted value =",prediction)
print("MSE =",mean_squared_error(y,prediction))

The slope is [   256.83917062    339.28986331    475.68891551     65.67600705
    -65.67600705 -11923.73834752  11923.73834752    586.92290648
    234.13281096   -448.67279452   -372.38292292]
The intercept is -670.4230268694173
Predicted value = [25292.73983296  3458.28119063  6706.61883724 ...  4165.74286548
  1246.43276622 37093.64856899]
MSE = 36499631.63514606

### 228

Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”. Do the required process in the data before making a model.

If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
Find co-efficient, intercept and mean squared error.

Also Predict the quality of red wine for the following data:

fixed acidity: 8
volatile acidity: 0.4
citric acid: 0.40
residual sugar: 15
chlorides: 0.048
free sulfur dioxide: 40
total sulfur dioxide: 150
density: 0.99
pH: 3
sulphates: 0.45
alcohol: 10.5

---

In [37]:
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/winequality.csv")
df.head(2)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1

In [38]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [39]:
x = df.drop(columns=["quality","Id"])
y = df["quality"]
print(x.shape)
print(y.shape)

(1143, 11)
(1143,)

In [40]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [41]:
print("Coefficient =",model.coef_)
print("Intercept =",model.intercept_)
prediction = model.predict(x)
print("MSE =",mean_squared_error(y,prediction))

Coefficient = [ 2.29746331e-02 -1.12910200e+00 -1.31862721e-01  1.35116748e-02
 -1.70816059e+00  2.36938156e-03 -2.78491532e-03 -1.74492955e+01
 -4.08202784e-01  8.75200141e-01  2.80142992e-01]
Intercept = 21.54947030097066
MSE = 0.40598198111589573

In [44]:
print(model.predict([[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]]))

[5.86253341]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### 229

Consider variables x and y created from a pandas dataframe “car.csv”.
Create new column named “Age_car” (Age_car=2023-year)

For multiple linear regression problem, x contains the independent variables (Age_car, Driven_kms, Fuel_Type, Selling_type, Transmission) and y contains the dependent (Selling_Price) variable which is to be predicted.

Write a Python program to split x and y into training and testing datasets with a 20% split. Then create a multiple linear regression model using the training data and print its coefficients, intercept and mean squared error.

---

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/car.csv")
df.head(2)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0

In [4]:
# create a new column Age Age_car=2023-year
df["Age_year"] = 2023 - df["Year"]
df.drop(columns=["Car_Name","Year","Owner","Present_Price"],inplace=True)
df.head(2)

   Selling_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Age_year
0           3.35       27000    Petrol      Dealer       Manual         9
1           4.75       43000    Diesel      Dealer       Manual        10

### 230

Write a python program for following tasks -

Make sure all the required libraries are imported at the beginning of the Jupyter Notebook.

a) Load the windpower dataset into the notebook.
b) Check records for any missing values and remove them permanently using appropriate method.
c) Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and testing (25%) sets using random state of 42.
d) Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.
e) Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of determination) for each polynomial degree.
f) Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot accordingly.
g) Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.
h) Print the coefficients and intercept for each trained polynomial regression model.
i) Use each model to predict power output for wind speeds of 5, 10, 15, and 20 m/s, and print the predictions.

---

In [ ]:
# a) Load the windpower dataset into the notebook.
df = pd.read_csv("https://raw.githubusercontent.com/patelmanishv/Sem4Data/refs/heads/main/Datasets/windpower.csv")
df.head(2)

# b) Check records for any missing values and remove them permanently using appropriate method.
df.isnull().sum()

# Remove the NA values permanently
df.dropna(inplace=True)

df.isnull().sum()

print(df.to_string())

#  c) Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and testing (25%) sets using random state of 42.
x = df[["Wind speed (m/s)"]]
y = df["Power (kW)"]
print(x.shape)
print(y.shape)

# Split the dataset into training (75%) and testing (25%) sets using random state of 42.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

# d) Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.
from sklearn.metrics import r2_score,mean_squared_error
import seaborn as sns
import matplotlib.pyplot as plt
givedegrees = [3,4,5,6]
mse_values = []
r2_scores = []

windspeeds = np.array([[5],[10],[15],[20]])
windprediction = {}

# plot
plt.style.use('ggplot') # optional
plt.figure(figsize=(12,8)) # optional
plt.title("Polynomial Regression of Windpower")
plt.scatter(x,y,color='k',label='truevalues')

for degree in givedegrees:
    poly = PolynomialFeatures(degree=degree)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.fit_transform(x_test) 
    model = LinearRegression()
    model.fit(x_train_poly,y_train)
    predictions = model.predict(x_test_poly)
    mse = mean_squared_error(y_test,predictions)
    r2 = r2_score(y_test,predictions)
    mse_values.append(mse)
    r2_scores.append(r2)
    print(f"Result for {degree} polynomial regression")
    print(f"Coefficients: {model.coef_}")
    print(f"Intercepts: {model.intercept_}")
    print(f"Mean Squared Error: {mse:.2f}")
    print(f"Coefficient of Determination: {r2:.2f}")

    plt.plot(x_test,predictions,'x',label=f'predictedvalues for {degree}')
    windspeedpoly = poly.fit_transform(windspeeds)
    powerpredict = model.predict(windspeedpoly)
    windprediction[degree] = powerpredict
plt.xlabel("Windspeed")
plt.ylabel("Power")
plt.legend()
plt.show()

print(windprediction)

# g) Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.
plt.figure(figsize=(8,6))
plt.plot(givedegrees,mse_values,marker='o',linestyle='-',color='b')
plt.title("MSE vs Degree")
plt.xlabel("Degree")
plt.ylabel("MSE")
plt.grid(True)
plt.show()
# The sixthdegree has the lowest MSE of all